package com.game.gui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author caiop
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Senha = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Senha = new javax.swing.JPasswordField();
        btn_Sair = new javax.swing.JButton();
        btn_Entrar = new javax.swing.JButton();
        btn_Conta = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setPreferredSize(new java.awt.Dimension(1200, 720));

        jPanel1.setBackground(new java.awt.Color(49, 54, 63));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 40, 49), 15));

        lbl_Titulo.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(118, 171, 174));
        lbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo.setText("Game Cards");
        lbl_Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(34, 40, 49)));

        lbl_Email.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(118, 171, 174));
        lbl_Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Email.setText("Email");

        lbl_Senha.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_Senha.setForeground(new java.awt.Color(118, 171, 174));
        lbl_Senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Senha.setText("Senha");

        txt_Email.setBackground(new java.awt.Color(118, 171, 174));
        txt_Email.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(238, 238, 238));
        txt_Email.setText("caio@gmail.com");

        txt_Senha.setBackground(new java.awt.Color(118, 171, 174));
        txt_Senha.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        txt_Senha.setForeground(new java.awt.Color(238, 238, 238));
        txt_Senha.setText("1111");

        btn_Sair.setBackground(new java.awt.Color(118, 171, 174));
        btn_Sair.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_Sair.setForeground(new java.awt.Color(238, 238, 238));
        btn_Sair.setText("Sair");

        btn_Entrar.setBackground(new java.awt.Color(118, 171, 174));
        btn_Entrar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_Entrar.setForeground(new java.awt.Color(238, 238, 238));
        btn_Entrar.setText("Entrar");

        btn_Conta.setBackground(new java.awt.Color(118, 171, 174));
        btn_Conta.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_Conta.setForeground(new java.awt.Color(238, 238, 238));
        btn_Conta.setText("Criar Conta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Conta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btn_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 345, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Conta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(btn_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtn_Conta() {
        return btn_Conta;
    }

    public JButton getBtn_Entrar() {
        return btn_Entrar;
    }

    public JButton getBtn_Sair() {
        return btn_Sair;
    }

    public JLabel getLbl_Email() {
        return lbl_Email;
    }

    public JLabel getLbl_Senha() {
        return lbl_Senha;
    }

    public JLabel getLbl_Titulo() {
        return lbl_Titulo;
    }

    public JTextField getTxt_Email() {
        return txt_Email;
    }

    public JPasswordField getTxt_Senha() {
        return txt_Senha;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Conta;
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JPasswordField txt_Senha;
    // End of variables declaration//GEN-END:variables
}
